### ISSUE TITLE
-out option returns error

### ISSUE THREAD

**Issue by ghost** [harvardinformatics/bioblog#1]
Hi,

I've tried running this script and it works great. Thank you.
 However, when I try to make use of the -out option, it always returns an error: "Couldn't open file for writing: No such file or directory at illuminaDemultiplex.pl line 63."
It seems the only way to run this program is by allowing the current working directory to be the output's destination, no matter if I've created the directory I would like for the output beforehand or not.
I cannot figure out where the mistake is. Thanks!

**Comment by ghost** [comment]
I found that changing the -o option to required 'out=s' makes it work.

**Comment by cwillhu** [comment]
Thanks for catching this.
